[package]
name = "circom-example"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bn254 = "0.5.0"
ark-circom = "0.5.0"
ark-groth16 = "0.5.0"
ark-serialize = "0.5.0"
ark-snark = "0.5.1"
rand = "0.8.5"
hex = "0.4.3"
tokio = "1.41.0"
